[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[metadata]
name = "MinimalSym"
version = "0.1.0"
authors = [
	"Sebastian Hernández <s3b4s7i4nhg@gmail.com>"
    ]
description = "A program for molecular symmetry detection. Minimal version of MolSym library."
long_description = "file: README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3"
    ]
readme = "README.md"
requires-python = ">=3.9"
[options]
install_requires = [
    "numpy >= 1.23.4",
    "qcelemental >= 0.25.1"
    ]

