[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "molsympy"
version = "0.1.3"
description = "Molecular symmetry detection and symmetrization"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [
{ name = "Sebastian Hernandez-Gutierrez", email = "s3b4s7i4nhg@gmail.com" },
{ name = "Diego Roman-Montalvo", email = "romanmdiego@gmail.com" },
{ name = "Gabriel Merino", email = "gabriel.merino2@gmail.com" },
{ name = "Filiberto Ortiz-Chi", email = "fortiz666@gmail.com" }
]
dependencies = [
    "numpy>=1.24",
    "numba>=0.61.0",
    "ase>=3.22"
]

[project.optional-dependencies]
docs = [
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
  "mkdocs-glightbox"
]
dev = [
    "build",
    "pytest"
]

[project.urls]
Homepage = "https://github.com/hyl-kibou/molsympy"

[tool.setuptools.packages.find]
exclude = ["site*"]
include = ["molsympy", "molsympy.*"]

[tool.setuptools.package-data]
"molsympy.collections" = ["*.npz"]
