"""
cyclic_dihedral.py — Generators for cyclic (Zn/Cn/Sn), dihedral, and direct-product groups.

Public functions: _Zn, _Dihn, _direct_product
"""

import numpy as np
from numpy.linalg import matrix_power

from .symel import Symel
from .sym_ops import reflection_matrix, Cn, Sn, normalize, reduce
from .group_algebra import _mult_iCnm, _mult_sigmahCnm, _mult_CSC2sigma


def _Zn(n, generator):
    """
    Build symmetry elements for cyclic groups generated by C_n or S_n.

    Parameters
    ----------
    n : int
        Order of the principal axis.
    generator : str
        Principal generator; either "C" for proper rotations or "S" for improper rotations.

    Returns
    -------
    List[Symel]
    """
    x, y, z = np.eye(3)
    symels = [Symel("E", None, np.eye(3, dtype=np.float64), 0, n, "E")]
    if generator == "C" and n > 1:
        cn1 = Symel(f"C_{n}", z, Cn(z, n), 1, n, "E")
        symels.append(cn1)
        for m in range(2, n):
            a, b = reduce(n, m)
            symb = f"C_{a}" if b == 1 else f"C_{a}^{b}"
            symels.append(Symel(symb, z, matrix_power(Cn(z, n), m), m, n, "E"))
    elif generator == "S":
        sn1 = Symel(f"S_{n}", z, Sn(z, n), 1, n, "E")
        symels.append(sn1)
        for m in range(2, n):
            a, b = reduce(n, m)
            symb = f"C_{a}^{b}" if m % 2 == 0 else f"S_{a}^{b}"
            if b == 1:
                symb = symb.replace("^1", "")
            symels.append(Symel(symb, z, matrix_power(Sn(z, n), m), m, n, "E"))
    return symels


def _Dihn(n, generator, symel_tag):
    """
    Build symmetry elements for dihedral-isomorphic groups.

    Parameters
    ----------
    n : int
        Order of the principal axis.
    generator : str
        Principal generator; either "C" for proper rotations or "S" for improper rotations.
    symel_tag : str
        Secondary generator label; either "sigma_v" or "C_2'".

    Returns
    -------
    List[Symel]
    """
    x, y, z = np.eye(3)
    symels = [Symel("E", None, np.eye(3, dtype=np.float64), 0, n, "E")]
    if generator == "C":
        if symel_tag == "sigma_v":
            post = "sigma"
            on0 = Symel("sigma_v(0)", y, reflection_matrix(y), 0, n, "sigma_v")
            tag_re = ("v", "d")
        elif symel_tag == "C_2'":
            post = "C_2"
            on0 = Symel(f"C_2'(0)", x, Cn(x, 2), 0, n, "C_2'")
            tag_re = ("'", "''")
        if n % 2 == 0:
            rsymb = symel_tag.replace(tag_re[0], tag_re[1]) + "(0)"
        else:
            rsymb = symel_tag + f"({(n>>1)+1})"
        symels.append(on0)
        for m in range(1, n):
            a, b = reduce(n, m)
            symb = f"C_{a}" if b == 1 else f"C_{a}^{b}"
            rot = matrix_power(Cn(z, n), m)
            symels.insert(m, Symel(symb, z, matrix_power(Cn(z, n), m), m, n, "E"))
            rsymb = _mult_CSC2sigma(m, n, "C", post)
            new_vector = np.dot(matrix_power(Cn(z, 2*n), m), on0.vector)
            symels.append(Symel(rsymb, new_vector, rot @ on0.rrep, m, n, symel_tag))
    elif generator == "S":
        sn1 = Symel(f"S_{n}", z, Sn(z, n), 1, n, "E")
        symels.append(sn1)
        on0 = Symel("C_2'(0)", x, Cn(x, 2), 0, n, "C_2'")
        symels.append(on0)
        v = np.dot(Cn(z, 2*n), y)
        on1 = Symel("sigma_d(0)", v, reflection_matrix(v), 1, n, "C_2'")
        symels.append(on1)
        for m in range(2, n):
            a, b = reduce(n, m)
            if m % 2 == 0:
                symb = f"C_{a}^{b}"
                rsymb = f"C_2'({m>>1})"
                rot = matrix_power(Cn(z, n), m)
                vec = np.dot(matrix_power(Cn(z, n), m>>1), on0.vector)
                rrep = rot @ on0.rrep
                insert_idx = -(m>>1)
            else:
                symb = f"S_{a}^{b}"
                rsymb = f"sigma_d({m>>1})"
                rot = matrix_power(Cn(z, n), m-1)
                vec = np.dot(matrix_power(Cn(z, n), m>>1), on1.vector)
                rrep = rot @ on1.rrep
                insert_idx = len(symels)+1
            if b == 1:
                symb = symb.replace("^1", "")
            symels.insert(m, Symel(symb, z, matrix_power(Sn(z, n), m), m, n, "E"))
            symels.insert(insert_idx, Symel(rsymb, vec, rrep, m, n, symel_tag))
    else:
        raise Exception(f"Invalid generator {generator}")
    return symels


def _direct_product(symels, dpsymel):
    """
    Extend a set of symels by taking the direct product with a group of order 2.

    Parameters
    ----------
    symels : List[Symel]
        Symmetry elements of the base group.
    dpsymel : Symel
        The non-identity element of the order-2 factor group (i or sigma_h).

    Returns
    -------
    List[Symel]
    """
    z = np.array([0, 0, 1], dtype=np.float64)
    newsymels = list(symels)
    for symel in symels:
        new_rrep = symel.rrep @ dpsymel.rrep
        if dpsymel.symbol == "i":
            if symel.O == "E":
                b, a = _mult_iCnm(symel.m, symel.n)
                if a == 2:
                    new_symbol, new_vector = "i", None
                elif a == 1:
                    new_symbol, new_vector = "sigma_h", z
                else:
                    new_symbol = f"S_{a}" if b == 1 else f"S_{a}^{b}"
                    new_vector = symel.vector
                new_O = dpsymel.symbol
            elif symel.O == "C_2'":
                new_symbol = _mult_CSC2sigma(symel.m, symel.n, "iC", "C_2")
                new_vector = symel.vector
                new_O = dpsymel.symbol
        elif dpsymel.symbol == "sigma_h":
            if symel.O == "E":
                new_O = "sigma_h"
                b, a = _mult_sigmahCnm(symel.m, symel.n)
                if a == 1:
                    new_symbol, new_vector = "sigma_h", z
                else:
                    new_symbol = f"S_{a}" if b == 1 else f"S_{a}^{b}"
                    new_vector = symel.vector
            elif symel.O == "C_2'":
                new_vector = normalize(np.cross(z, symel.vector))
                new_symbol = symel.symbol.replace("C_2'", "sigma_v")
                new_O = "sigma_v"
        else:
            raise Exception(f"Invalid direct product element: {dpsymel.symbol}")
        newsymels.append(Symel(new_symbol, new_vector, new_rrep, symel.m, symel.n, new_O))
    return newsymels
