import numpy as np
from numpy.linalg import matrix_power
from .point_group import PointGroup
from ..symtools import reflection_matrix, inversion_matrix, Cn, Sn, normalize, reduce
from .symel import Symel, T_SYMELS, TD_SYMELS, TH_SYMELS, O_SYMELS, OH_SYMELS, I_SYMELS, IH_SYMELS
from numba import njit

np.set_printoptions(precision=3, threshold=np.inf, linewidth=14000, suppress=True)

def pg_to_symels(PG):
    """
    Returns the associated symmetry elements for a given point group.

    Parameters
    ----------
    PG : str
        Schoenflies point group symbol (e.g. "C2v", "D6h", "Oh").

    Returns
    -------
    List[Symel]
    """    
    pg = PointGroup.from_string(PG)
    argerr = f"An invalid point group has been given or unexpected parsing of the point group string has occured: {pg.str}"
    z = np.array([0,0,1])
    i = Symel("i", None, inversion_matrix(), 0, 0, "i")
    sh = Symel("sigma_h", np.array([0,0,1]), reflection_matrix(z), 0, 0, "sigma_h")
    if pg.is_linear:
        if pg.family == "C":
            symels = [Symel("C", z, None, None, None, None), 
                      Symel("sigma_v", None, None, None, None, None)]            
            return symels
        elif pg.family == "D":
            symels = [Symel("C", z, None, None, None, None), 
                      Symel("sigma_v", None, None, None, None, None),
                      Symel("S", z, None, None, None, None),
                      Symel("C_2'", None, None, None, None, None)]
            return symels
    if pg.n is not None:
        n_is_even = (pg.n % 2 == 0)
        n_is_doubleeven = (pg.n % 4 == 0)
    if pg.family == "C":
        if pg.subfamily == "h":
            cn_symels = _Zn(pg.n, "C")
            if n_is_even:
                return _direct_product(cn_symels, i)
            else:
                return _direct_product(cn_symels, sh)
        elif pg.subfamily == "v":
            return _Dihn(pg.n, "C", "sigma_v")
        elif pg.subfamily == "s":
            symels = [Symel("E", None, np.eye(3), 0, None, "E"), sh]
            return symels
        elif pg.subfamily == "i":
            symels = [Symel("E", None, np.eye(3), 0, None, "E"), i]
            return symels
        elif pg.subfamily is None:
            # Cn branch
            symels = _Zn(pg.n, "C")
            return symels
        else:
            raise Exception(argerr)
    elif pg.family == "D":
        if pg.subfamily == "h":
            dn_symels = _Dihn(pg.n, "C", "C_2'")
            if n_is_even:
                return _direct_product(dn_symels, i)
            else:
                return _direct_product(dn_symels, sh)
        elif pg.subfamily == "d":
            if n_is_even:
                return _Dihn(pg.n*2, "S", "C_2'")
            else:
                dn_symels = _Dihn(pg.n, "C", "C_2'")
                return _direct_product(dn_symels, i)
        elif pg.subfamily is None:
            return _Dihn(pg.n, "C", "C_2'")
        else:
            raise Exception(argerr)
    elif pg.family == "S":
        if pg.subfamily is None and n_is_even:
            if n_is_doubleeven:
                return _Zn(pg.n, "S")
            else:
                cn_symels = _Zn(pg.n>>1, "C")
                return _direct_product(cn_symels, i)
        else:
            raise Exception(argerr)
    else:
        if pg.family == "T":
            if pg.subfamily == "h":
                return TH_SYMELS
            elif pg.subfamily == "d":
                return TD_SYMELS
            else:
                return T_SYMELS
        elif pg.family == "O":
            if pg.subfamily == "h":
                return OH_SYMELS
            else:
                return O_SYMELS
        elif pg.family == "I":
            if pg.subfamily == "h":
                return IH_SYMELS
            else:
                return I_SYMELS
        else:
            raise Exception(argerr)
    return 0

def _Zn(n, generator):
    """
    Build symmetry elements for cyclic groups generated by C_n or S_n.

    Parameters
    ----------
    n : int
        Order of the principal axis.
    generator : str
        Principal generator; either "C" for proper rotations or "S" for improper rotations.

    Returns
    -------
    List[Symel]
    """
    # cyclic group generated by generator
    x, y, z = np.eye(3)
    symels = [Symel("E", None, np.eye(3, dtype=np.float64), 0, n, "E")]
    # Generate symels
    if generator == "C" and n > 1:
        cn1 = Symel(f"C_{n}", z, Cn(z, n), 1, n, "E")
        symels.append(cn1)
        for m in range(2, n):
            a,b = reduce(n, m)
            if b == 1:
                symb = f"C_{a}"
            else:
                symb = f"C_{a}^{b}"
            cnm = Symel(symb, z, matrix_power(Cn(z, n), m), m, n, "E")
            symels.append(cnm)
    elif generator == "S":
        sn1 = Symel(f"S_{n}", z, Sn(z, n), 1, n, "E")
        symels.append(sn1)
        for m in range(2, n):
            a,b = reduce(n, m)
            if m % 2 == 0:
                symb = f"C_{a}^{b}"
            else:
                symb = f"S_{a}^{b}"
            if b == 1:
                symb = symb.replace("^1", "")
            cnm = Symel(symb, z, matrix_power(Sn(z, n), m), m, n, "E")
            symels.append(cnm)
    return symels

@njit
def _omega(m, n):
    """Reduce the power m of an S_n element to its canonical symbol index and axis order."""
    gcd_val = np.gcd(m, n)
    l = (m/gcd_val) + (n/gcd_val) * (1-((m/gcd_val)%2))
    return int(l), int(n/gcd_val)

@njit
def _mult_iCnm(m, n):
    """Return the canonical power and axis order of i * C_n^m."""
    a = (2*m+n) % (2*n)
    return _omega(a, 2*n)

@njit
def _mult_sigmahCnm(m, n):
    """Return the canonical power and axis order of sigma_h * C_n^m."""
    return _omega(m, n)

@njit
def _mult_CSC2sigma(m, n, pre, post):
    """Return the symbol of the product of a principal-axis element with a C_2' or sigma element."""
    # Operator: "C_2", "sigma"
    if pre == "C":
        if post == "C_2":
            even_odd = ["'", "''"]
        elif post == "sigma":
            even_odd = ["_v", "_d"]
    else:
        if post == "C_2":
            post = "sigma"
            even_odd = ["_v", "_d"]
    if n % 2 == 0:
        if pre == "iC":
            if n % 4 == 0:
                label = even_odd[m%2]
                a = ((n>>2) + (m>>1)) % (n>>1)
            else:
                label = even_odd[(m+1)%2]
                a = ((n>>2) + ((m+1)>>1)) % (n>>1)
            return post + label + f"({a})"
        else:
            label = even_odd[m%2]
            a = (m>>1) % (n>>1)
            return post + label + f"({a})"
    else:
        if pre == "iC":
            label = "_d"
            a = ((n>>1) + m) % n
        else:
            label = even_odd[0]
            a = ((((n>>1)+1) * (m % 2))+(m>>1)) % n
        return post + label + f"({a})"

def _Dihn(n, generator, symel_tag):
    """
    Build symmetry elements for dihedral-isomorphic groups.

    Parameters
    ----------
    n : int
        Order of the principal axis.
    generator : str
        Principal generator; either "C" for proper rotations or "S" for improper rotations.
    symel_tag : str
        Secondary generator label; either "sigma_v" or "C_2'".

    Returns
    -------
    List[Symel]
    """
    x, y, z = np.eye(3)
    # Generate symels
    symels = [Symel("E", None, np.eye(3, dtype=np.float64), 0, n, "E")]
    if generator == "C":
        if symel_tag == "sigma_v":
            # First reflection contains the x-axis so the normal vector is y-axis
            # Rotated reflections trail the associated rotation by theta/2
            post = "sigma"
            on0 = Symel("sigma_v(0)", y, reflection_matrix(y), 0, n, "sigma_v")
            tag_re = ("v", "d")
        elif symel_tag == "C_2'":
            # First C_2' is about the x-axis
            post = "C_2"
            on0 = Symel(f"C_2'(0)", x, Cn(x, 2), 0, n, "C_2'")
            tag_re = ("'", "''")
        if n % 2 == 0:
            rsymb = symel_tag.replace(tag_re[0], tag_re[1]) + "(0)"
        else:# symel_tag == "sigma_v":
            rsymb = symel_tag+f"({(n>>1)+1})"
        symels.append(on0)
        for m in range(1,n):
            a, b = reduce(n, m)
            if b == 1:
                symb = f"C_{a}"
            else:
                symb = f"C_{a}^{b}"
            rot = matrix_power(Cn(z, n), m)
            cnm = Symel(symb, z, matrix_power(Cn(z, n), m), m, n, "E")
            symels.insert(m, cnm)
            rsymb = _mult_CSC2sigma(m, n, "C", post)
            new_vector = np.dot(matrix_power(Cn(z, 2*n), m), on0.vector)
            onm = Symel(rsymb, new_vector, rot @ on0.rrep, m, n, symel_tag)
            symels.append(onm)
    elif generator == "S":
        sn1 = Symel(f"S_{n}", z, Sn(z, n), 1, n, "E")
        symels.append(sn1)
        on0 = Symel("C_2'(0)", x, Cn(x, 2), 0, n, "C_2'")
        symels.append(on0)
        v = np.dot(Cn(z, 2*n), y)
        on1 = Symel("sigma_d(0)", v, reflection_matrix(v), 1, n, "C_2'")
        symels.append(on1)
        for m in range(2, n):
            a, b = reduce(n, m)
            if m % 2 == 0:
                symb = f"C_{a}^{b}"
                rsymb = f"C_2'({m>>1})"
                rot = matrix_power(Cn(z, n), m)
                vec = np.dot(matrix_power(Cn(z, n), m>>1), on0.vector)
                rrep = rot @ on0.rrep
                insert_idx = -(m>>1)
            else:
                symb = f"S_{a}^{b}"
                rsymb = f"sigma_d({m>>1})"
                rot = matrix_power(Cn(z, n), m-1)
                
                vec = np.dot(matrix_power(Cn(z, n), m>>1), on1.vector)                
                rrep = rot @ on1.rrep
                insert_idx = len(symels)+1
            if b == 1:
                symb = symb.replace("^1", "")
            snm = Symel(symb, z, matrix_power(Sn(z, n), m), m, n, "E")
            symels.insert(m, snm)
            onm = Symel(rsymb, vec, rrep, m, n, symel_tag)
            symels.insert(insert_idx, onm)
    else:
        raise Exception(f"Invalid generator {generator}")
    return symels

def _direct_product(symels, dpsymel):
    """
    Extend a set of symels by taking the direct product with a group of order 2.

    Parameters
    ----------
    symels : List[Symel]
        Symmetry elements of the base group.
    dpsymel : Symel
        The non-identity element of the order-2 factor group (i or sigma_h).

    Returns
    -------
    List[Symel]
    """
    x, y, z = np.eye(3)
    newsymels = [symel for symel in symels]
    for symel in symels:
        new_rrep = symel.rrep @ dpsymel.rrep
        if dpsymel.symbol == "i":
            if symel.O == "E":
                # Z proper rotations
                b, a = _mult_iCnm(symel.m, symel.n)
                if a == 2:
                    new_symbol = "i"
                    new_vector = None
                elif a == 1:
                    new_symbol = "sigma_h"
                    new_vector = z
                else:
                    if b == 1:
                        new_symbol = f"S_{a}"
                    else:
                        new_symbol = f"S_{a}^{b}"
                    new_vector = symel.vector
                new_O = dpsymel.symbol
            elif symel.O == "C_2'":
                new_symbol = _mult_CSC2sigma(symel.m, symel.n, "iC", "C_2")
                new_vector = symel.vector
                new_O = dpsymel.symbol
        elif dpsymel.symbol == "sigma_h":
            # n is odd
            if symel.O == "E":
                # Z proper rotations
                new_O = "sigma_h"
                b, a = _mult_sigmahCnm(symel.m, symel.n)
                if a == 1:
                    new_symbol = "sigma_h"
                    new_vector = z
                else:
                    if b == 1:
                        new_symbol = f"S_{a}"
                    else:
                        new_symbol = f"S_{a}^{b}"
                    new_vector = symel.vector
            elif symel.O == "C_2'":
                # Dnh, n is odd
                new_vector = normalize(np.cross(z, symel.vector))
                new_symbol = symel.symbol.replace("C_2'", "sigma_v")
                new_O = "sigma_v"
        else:
            raise Exception(f"Invalid direct product element: {dpsymel.symbol}")
        ns = Symel(new_symbol, new_vector, new_rrep, symel.m, symel.n, new_O)
        newsymels.append(ns)
        
    return newsymels
