import numpy as np
from numpy.linalg import matrix_power
from dataclasses import dataclass
from .point_group import PointGroup
from ..symtools import reflection_matrix, inversion_matrix, Cn, Sn, normalize, reduce
from .symel import Symel, generate_T, generate_Th, generate_Td, generate_O, generate_Oh, generate_I, generate_Ih

np.set_printoptions(precision=3, threshold=np.inf, linewidth=14000, suppress=True)

def pg_to_symels(PG):
    """
    Takes in a point group string and returns the associated symmetry elements, irreducible representations, and irreducible representation matrices.

    :type PG: str
    :rtype: List[molsym.Symel]
    """
    greek = ["Pi", "Delta", "Phi", "Gamma", "Eta", "Iota", "Kappa", "Lambda", "Mu", "Nu", "Omicron"]
    pg = PointGroup.from_string(PG)
    argerr = f"An invalid point group has been given or unexpected parsing of the point group string has occured: {pg.str}"
    z = np.array([0,0,1])
    i = Symel("i", None, inversion_matrix(), 0, 0, "i")
    sh = Symel("sigma_h", np.array([0,0,1]), reflection_matrix(z), 0, 0, "sigma_h")
    if pg.is_linear:
        if pg.family == "C":
            symels = [#Symel("E", None, None, None, None, None), E is included in C 
                      Symel("C", z, None, None, None, None), 
                      Symel("sigma_v", None, None, None, None, None)]            
            return symels
        elif pg.family == "D":
            symels = [#Symel("E", None, None, None, None, None), 
                      Symel("C", z, None, None, None, None), 
                      Symel("sigma_v", None, None, None, None, None),
                      #Symel("i", None, None, None, None, None), i is included in S
                      Symel("S", z, None, None, None, None),
                      Symel("C_2'", None, None, None, None, None)]
            return symels
    if pg.n is not None:
        n_is_even = (pg.n % 2 == 0)
        n_is_doubleeven = (pg.n % 4 == 0)
    if pg.family == "C":
        if pg.subfamily == "h":
            cn_symels = Zn(pg.n, "C")
            if n_is_even:
                return direct_product(cn_symels, i)
            else:
                return direct_product(cn_symels, sh)
        elif pg.subfamily == "v":
            return Dihn(pg.n, "C", "sigma_v")
        elif pg.subfamily == "s":
            symels = [Symel("E", None, np.eye(3), 0, None, "E"), sh]
            return symels
        elif pg.subfamily == "i":
            symels = [Symel("E", None, np.eye(3), 0, None, "E"), i]
            return symels
        elif pg.subfamily is None:
            # Cn branch
            symels = Zn(pg.n, "C")
            return symels
        else:
            raise Exception(argerr)
    elif pg.family == "D":
        if pg.subfamily == "h":
            dn_symels = Dihn(pg.n, "C", "C_2'")
            if n_is_even:
                return direct_product(dn_symels, i)
            else:
                return direct_product(dn_symels, sh)
        elif pg.subfamily == "d":
            if n_is_even:
                return Dihn(pg.n*2, "S", "C_2'")
            else:
                dn_symels = Dihn(pg.n, "C", "C_2'")
                return direct_product(dn_symels, i)
        elif pg.subfamily is None:
            return Dihn(pg.n, "C", "C_2'")
        else:
            raise Exception(argerr)
    elif pg.family == "S":
        if pg.subfamily is None and n_is_even:
            if n_is_doubleeven:
                return Zn(pg.n, "S")
            else:
                cn_symels = Zn(pg.n>>1, "C")
                return direct_product(cn_symels, i)
        else:
            raise Exception(argerr)
    else:
        if pg.family == "T":
            if pg.subfamily == "h":
                return generate_Th()
            elif pg.subfamily == "d":
                return generate_Td()
            else:
                return generate_T()
        elif pg.family == "O":
            if pg.subfamily == "h":
                return generate_Oh()
            else:
                return generate_O()
        elif pg.family == "I":
            if pg.subfamily == "h":
                return generate_Ih()
            else:
                return generate_I()
        else:
            raise Exception(argerr)
    return 0

def Zn(n, generator):
    """
    Builds symmetry elements, irreducible representations, and irreducible representation matrices for cyclic point groups.

    :type n: int
    :type generator: str

    :rtype: List[molsym.Symel]
    """
    # cyclic group generated by generator
    x,y,z = np.eye(3)
    e = Symel("E", None, np.eye(3, dtype=np.float64), 0, n, "E")
    symels = [e]
    # Generate symels
    if generator == "C" and n>1:
        cn1 = Symel(f"C_{n}", z, Cn(z, n), 1, n, "E")
        symels.append(cn1)
        for m in range(2,n):
            a,b = reduce(n, m)
            if b == 1:
                symb = f"C_{a}"
            else:
                symb = f"C_{a}^{b}"
            cnm = Symel(symb, z, matrix_power(Cn(z,n),m), m, n, "E")
            symels.append(cnm)
    elif generator == "S":
        sn1 = Symel(f"S_{n}", z, Sn(z, n), 1, n, "E")
        symels.append(sn1)
        for m in range(2,n):
            a,b = reduce(n, m)
            if m % 2 == 0:
                symb = f"C_{a}^{b}"
            else:
                symb = f"S_{a}^{b}"
            if b == 1:
                symb = symb.replace("^1", "")
            cnm = Symel(symb, z, matrix_power(Sn(z,n),m), m, n, "E")
            symels.append(cnm)
    return symels

def omega(m, n):
    gcd = np.gcd(m, n)
    l = (m/gcd) + (n/gcd) * (1-((m/gcd)%2))
    return int(l), int(n/gcd)

def mult_iCnm(m, n):
    a = (2*m+n) % (2*n)
    return omega(a, 2*n)

def mult_sigmahCnm(m, n):
    return omega(m, n)

def mult_CSC2sigma(m, n, pre, post):
    # Operator: "C_2", "sigma"
    if pre == "C":
        if post == "C_2":
            even_odd = ["'", "''"]
        elif post == "sigma":
            even_odd = ["_v", "_d"]
    else:
        if post == "C_2":
            post = "sigma"
            even_odd = ["_v", "_d"]
    if n % 2 == 0:
        if pre == "iC":
            if n % 4 == 0:
                label = even_odd[m%2]
                a = ((n>>2) + (m>>1)) % (n>>1)
            else:
                label = even_odd[(m+1)%2]
                a = ((n>>2) + ((m+1)>>1)) % (n>>1)
            return post + label + f"({a})"
        else:
            label = even_odd[m%2]
            a = (m>>1) % (n>>1)
            return post + label + f"({a})"
    else:
        if pre == "iC":
            label = "_d"
            a = ((n>>1) + m) % n
        else:
            label = even_odd[0]
            a = ((((n>>1)+1) * (m % 2))+(m>>1)) % n
        return post + label + f"({a})"

def Dihn(n, generator, symel_tag):
    """
    Builds symmetry elements, irreducible representations, and irreducible representation matrices for dihedral isomorphic point groups.

    :param generator: Symmetry element that generates half of the point group
    :param symel_tag: Operation that generates the other half of the point group
    :type n: int
    :type generator: str
    :type symel_tag: str

    :rtype: List[molsym.Symel]
    """
    x, y, z = np.eye(3)
    # Generate symels
    e = Symel("E", None, np.eye(3, dtype=np.float64), 0, n, "E")
    symels = [e]
    if generator == "C":
        if symel_tag == "sigma_v":
            # First reflection contains the x-axis so the normal vector is y-axis
            # Rotated reflections trail the associated rotation by theta/2
            post = "sigma"
            on0 = Symel("sigma_v(0)", y, reflection_matrix(y), 0, n, "sigma_v")
            tag_re = ("v", "d")
        elif symel_tag == "C_2'":
            # First C_2' is about the x-axis
            post = "C_2"
            on0 = Symel(f"C_2'(0)", x, Cn(x, 2), 0, n, "C_2'")
            tag_re = ("'", "''")
        if n % 2 == 0:
            rsymb = symel_tag.replace(tag_re[0], tag_re[1]) + "(0)"
        else:# symel_tag == "sigma_v":
            rsymb = symel_tag+f"({(n>>1)+1})"
        symels.append(on0)
        for m in range(1,n):
            a,b = reduce(n, m)
            if b == 1:
                symb = f"C_{a}"
            else:
                symb = f"C_{a}^{b}"
            rot = matrix_power(Cn(z, n), m)
            cnm = Symel(symb, z, matrix_power(Cn(z, n), m), m, n, "E")
            symels.insert(m, cnm)
            rsymb = mult_CSC2sigma(m, n, "C", post)
            new_vector = np.dot(matrix_power(Cn(z, 2*n), m), on0.vector)
            onm = Symel(rsymb, new_vector, rot @ on0.rrep, m, n, symel_tag)
            symels.append(onm)
    elif generator == "S":
        sn1 = Symel(f"S_{n}", z, Sn(z, n), 1, n, "E")
        symels.append(sn1)
        on0 = Symel("C_2'(0)", x, Cn(x,2), 0, n, "C_2'")
        symels.append(on0)
        v = np.dot(Cn(z,2*n), y)
        on1 = Symel("sigma_d(0)", v, reflection_matrix(v), 1, n, "C_2'")
        symels.append(on1)
        for m in range(2,n):
            a,b = reduce(n, m)
            if m % 2 == 0:
                symb = f"C_{a}^{b}"
                rsymb = f"C_2'({m>>1})"
                rot = matrix_power(Cn(z, n), m)
                vec = np.dot(matrix_power(Cn(z, n), m>>1), on0.vector)
                rrep = rot @ on0.rrep
                insert_idx = -(m>>1)
            else:
                symb = f"S_{a}^{b}"
                rsymb = f"sigma_d({m>>1})"
                rot = matrix_power(Cn(z, n), m-1)
                
                vec = np.dot(matrix_power(Cn(z, n), m>>1), on1.vector)
                #rrep = reflection_matrix(vec)
                rrep = rot @ on1.rrep
                insert_idx = len(symels)+1
            if b == 1:
                symb = symb.replace("^1", "")
            snm = Symel(symb, z, matrix_power(Sn(z, n), m), m, n, "E")
            symels.insert(m, snm)
            onm = Symel(rsymb, vec, rrep, m, n, symel_tag)
            symels.insert(insert_idx, onm)
    else:
        raise Exception(f"Invalid generator {generator}")
    return symels

def direct_product(symels, dpsymel):
    """
    Builds symmetry elements, irreducible representations, and irreducible representation matrices from a direct product of a base point group with a point group of order 2.

    :param symels: Symmetry elements of base point group
    :param dpsymel: Non-identity symmetry element of point group of order 2
    :type symels: List[molsym.Symel]
    :type dpsymel: molsym.Symel
    :rtype: List[molsym.Symel]
    """
    x, y, z = np.eye(3)
    newsymels = [symel for symel in symels]
    for symel in symels:
        new_rrep = symel.rrep @ dpsymel.rrep
        if dpsymel.symbol == "i":
            if symel.O == "E":
                # Z proper rotations
                b, a = mult_iCnm(symel.m, symel.n)
                if a == 2:
                    new_symbol = "i"
                    new_vector = None
                elif a == 1:
                    new_symbol = "sigma_h"
                    new_vector = z
                else:
                    if b == 1:
                        new_symbol = f"S_{a}"
                    else:
                        new_symbol = f"S_{a}^{b}"
                    new_vector = symel.vector
                new_O = dpsymel.symbol
            elif symel.O == "C_2'":
                new_symbol = mult_CSC2sigma(symel.m, symel.n, "iC", "C_2")
                new_vector = symel.vector
                new_O = dpsymel.symbol
        elif dpsymel.symbol == "sigma_h":
            # n is odd
            if symel.O == "E":
                # Z proper rotations
                new_O = "sigma_h"
                b, a = mult_sigmahCnm(symel.m, symel.n)
                if a == 1:
                    new_symbol = "sigma_h"
                    new_vector = z
                else:
                    if b == 1:
                        new_symbol = f"S_{a}"
                    else:
                        new_symbol = f"S_{a}^{b}"
                    new_vector = symel.vector
            elif symel.O == "C_2'":
                # Dnh, n is odd
                new_vector = normalize(np.cross(z, symel.vector))
                new_symbol = symel.symbol.replace("C_2'", "sigma_v")
                new_O = "sigma_v"
        else:
            raise Exception(f"Invalid direct product element: {dpsymel.symbol}")
        ns = Symel(new_symbol, new_vector, new_rrep, symel.m, symel.n, new_O)
        newsymels.append(ns)
        
    return newsymels
